---
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
  word_document:
    reference_docx: ./resources/aog_word_style.docx
fontfamily: mathpazo
fontsize: 11pt
anonymous: false
endnotes: false
pagenumber: 1
bibliography: ../project.bib
biblio-style: ./resources/ajs.bst
title: "The Title"
author:
- affiliation: University of Oregon, Sociology
  name: Aaron Gullickson
- affiliation: Some Research University
  name: My co-author
keywords: keywords
thanks: Thanks to people and stuff
abstract: This is a test abstract
---

# Introduction

In movies and television shows, we constantly see parents, friends, neighbors, and others judge an individual for coming out as queer or finding out they were queer. It gives queer individuals a false sense of what actually happens when coming out to peers. Although the movies may make it seem like a scary experience, in reality nowadays, it is a breath of fresh air. In 2010, however, our society was inbetween whether or not it supported queer indiviudals. America was almost split with a few more leaning in the support same sex indiviudals and relationships. This survey was created to see how the LGBT community felt being around society. Queer individuals coming out to their peers will feel more support, happiness, and overall enjoyment in life because they are able to be who they are. This data should show that although society is not perfect and has not fully accepted the queer community, there has been a lot of process made. The data is from 2010 so we should be able to notice a difference in how individuals felt then compared to how we see the queer community act today.     

# Background

# Data and Methods

The data was collected using surveys in 2010. The original survey was a 105 item survey and was administered to over 5000 people. The strategy of data collection was through a variety of strategies, includng: venue-based sampling at strategic events, snowball sampling, respondent-driven sampling, and the internet.

# Results

# Conclusions

# References
