---
output:
  pdf_document:
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
fontfamily: mathpazo
fontsize: 11pt
anonymous: false
endnotes: false
#Change the page number for the final pdf
pagenumber: 1
---

```{r preamble, echo=FALSE, warning=FALSE}
load("analysis/output/analytical_data.RData")
```

# Tables and Figures

```{r setup, include=FALSE}
count <- table(sjsd$marriage)
percent <- 100*count/sum(count)
barplot(percent, main="Gay marriage support", horiz=TRUE, names.arg = c("No", "Yes"),
        xlab="Percent")
```

```{r setup, include=FALSE}
counts <- table(sjsd$military)
percent <- 100*counts/sum(counts)
barplot(percent, main="Support of LGBT in the military", horiz=TRUE, names.arg = c("No", "Yes"),
        xlab="Percent")
```

```{r setup, include=FALSE}
percent <- cbind(prop.table(table(sjsd$marriage)), prop.table(table(sjsd$military)))*100
barplot(percent, beside=TRUE, names.arg=c("Same-sex military","Gay marriage"), 
        las=1, main="Support gay marriage and\nsame sex military members", ylab="Percent of reponses for support",
        col=c("darkgreen", "yellow"), legend.text=c("No","Yes"), cex.names="0.7")
```

```{r setup, include=FALSE}
boxplot(as.numeric(fam_support)~out_family, data=sjsd, na.rm=TRUE,
        names=c("None","Some","About half","Most","All"), 
        xlab="Coming out to family", ylab="Level of support from family")
```

```{r setup, include=FALSE}
boxplot(as.numeric(happiness)~out_family, data=sjsd, na.rm=TRUE,
        names=c("None","Some","About half","Most","All"),
        xlab="Coming out to family", ylab="Level of happiness")
```
